# Generated by Django 3.0.5 on 2020-06-01 07:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200601_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 7, 43, 12, 632626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 7, 43, 12, 631758, tzinfo=utc)),
        ),
    ]
