# Generated by Django 3.0.5 on 2020-06-01 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200601_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 7, 46, 32, 93403, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 7, 46, 32, 92554, tzinfo=utc)),
        ),
    ]
